name: weixin

   on:
     schedule:
       - cron: '0 8 * * *'  # 每天8点执行

   jobs:
     push:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Set up Python
           uses: actions/setup-python@v2
           with:
             python-version: '3.8'
         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install requests configparser
         - name: Run Python script
           run: python main.py
