name: Daily Push

on:
  schedule:
    - cron: '0 23 * * *'  # 每天 UTC 时间的 0:00 执行（北京时间 8:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 指定 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests configparser

      # 4. 运行 Python 脚本
      - name: Run Python script
        run: python main.py

      # 5. 测试网络连接（可选）
      - name: Test network connectivity
        run: |
          ping -c 3 api.weatherapi.com
          ping -c 3 api.quotable.io
          ping -c 3 api.weixin.qq.com
